### Робота з бібліотекою Numpy

In [1]:
%pip install numpy
def homework(message):
    print("\n>>>>>", message, "\n")

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
temperature = [20.1, 20.1, 20.2, 20.4]
print(temperature)

t1 = temperature * 5

print(f"При множенні на 5 маємо: {t1}")
homework("Чому маємо такий результат?")

t1 = [ x*5 for x in temperature] 
print(f"Тепер отримаємо: {t1}") 
homework("Чому тепер множення успішне?")

t2 = np.array(temperature)
print("Масив з використанням методів NumPy", t2)

t3 = t2 * 5
print("При множенні на 5 отримуємо:", t3)

[20.1, 20.1, 20.2, 20.4]
При множенні на 5 маємо: [20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4, 20.1, 20.1, 20.2, 20.4]

>>>>> Чому маємо такий результат? 

Тепер отримаємо: [100.5, 100.5, 101.0, 102.0]

>>>>> Чому тепер множення успішне? 

Масив з використанням методів NumPy [20.1 20.1 20.2 20.4]
При множенні на 5 отримуємо: [100.5 100.5 101.  102. ]


### Вектори, створення та робота з ними - COMPLETED

In [3]:
print("Все можна сторити ручну за допомогою методу np.array передавши йому набір значень у вигляді List:")
vector_row = np.array([[1, -5, 3, 2, 4]])
vector_column = np.array([[1], 
                          [2], 
                          [3], 
                          [4]])
print(vector_row, "\nВектор має розмір", vector_row.shape)
print(vector_column, "\nВектор має розмір", vector_column.shape)

Все можна сторити ручну за допомогою методу np.array передавши йому набір значень у вигляді List:
[[ 1 -5  3  2  4]] 
Вектор має розмір (1, 5)
[[1]
 [2]
 [3]
 [4]] 
Вектор має розмір (4, 1)


#### Метод arange - COMPLETED

In [4]:
import numpy as np

start = 5
size_of_vec = 100
x = range(size_of_vec)
a = np.arange(size_of_vec)

print(f"Масив згенерований простим range: {x[0:5]} та методом arange: {a[0:5]}")

# Завдання 1:
homework("Виведіть весь діапазон чисел.")
print(f"Весь діапазон чисел з range: {list(x)}")  # Виводимо весь діапазон
print(f"Весь діапазон чисел з arange: {a}")  # Виводимо весь масив

a = np.arange(start, size_of_vec)
print(f"Можемо задавати початок генерації вектора, перший елемент: {a[0]}")

# Завдання 2:
homework("Виведіть останній діапазон в згенерованому масиві.")
print(f"Останні 5 елементів масиву: {a[-5:]}")  # Виводимо останні 5 елементів

x = range(start, size_of_vec)
print("Те саме але з вбудованою функцією range:", x)
print("Власне вивід значень:", list(x)[0])

# Завдання 3:
homework("Виведіть якесь число з середини діапазону.")
middle_value = list(x)[len(x)//2]  # Середнє значення діапазону
print(f"Число з середини діапазону: {middle_value}")

x = np.arange(0.04, 1.84, 0.08)
print("З кроком 0.08:", x)

# Завдання 4:
homework("Згенеруйте значення де крок буде мати чотири нулі після коми, яким буде результат?")
x_with_step_0001 = np.arange(0.0001, 0.01, 0.0001)  # Точність з чотирма нулями після коми
print("З кроком 0.0001:", x_with_step_0001)

y = x * 2.5
print("Після перемноження:", y)

# Завдання 5:
homework("Піднесіть отримане число до степеня та поділіть на 0.4 - Яким буде результат?")
result = (y ** 2) / 0.4  # Піднесення до квадрату і ділення на 0.4
print("Результат після операцій: ", result)


Масив згенерований простим range: range(0, 5) та методом arange: [0 1 2 3 4]

>>>>> Виведіть весь діапазон чисел. 

Весь діапазон чисел з range: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
Весь діапазон чисел з arange: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
Можемо задавати початок генерації вектора, перший елемент: 5

>>>>> Виведіть останній діапазон в згенерованому масиві. 

Останні

#### Метод linspace - COMPLETED

In [5]:
import numpy as np

start = 5
size_of_vec = 100

# Генерація лінійного простору
a = np.linspace(start, size_of_vec, num=10)
print(f"Згенерували {len(a)} чисел в діапазоні {a[0]} до {a[-1]}")

# Завдання 1:
homework("Виведіть кожне друге число згенерованого діапазону. Тут будее потрібен цикл :)")
for i in range(0, len(a), 2):  # Крок 2 для вибору кожного другого числа
    print(f"Кожне друге число: {a[i]}")

print("Можна зменшити кількість чисел до 5:")
a = np.linspace(start, size_of_vec, 5)
print(a)

# Завдання 2:
homework("Збільшіть кількість чисел до 100. Виведіть перших та останніх 10.")
a = np.linspace(start, size_of_vec, 100)
print(f"Перші 10 чисел: {a[:10]}")
print(f"Останні 10 чисел: {a[-10:]}")

print("""Як бачимо перше та останнє значення завжди входять у згенерований діапазон. 
Відповідно при цьому вираховується крок.
Це можна змінити, виключивши останнє значення з визначення діапазону.
""")

print(np.linspace(start, size_of_vec, 5, endpoint=False))

# Завдання 3:
homework("Спробуйте самі порахувати крок.")
# Різниця між першими та останніми значеннями ділимо на кількість елементів мінус 1:
calculated_step = (size_of_vec - start) / 5
print(f"Розрахунковий крок: {calculated_step}")


_, sp_1 = np.linspace(start, size_of_vec, 5, endpoint=True, retstep=True)
_, sp_2 = np.linspace(start, size_of_vec, 5, endpoint=False, retstep=True)
print(f"Для порівняння, ми можемо визначити крок автоматично, у нашому випадку це {sp_1} та {sp_2}")

# Завдання 4:
homework("Чому маємо такий крок?")
print("Крок залежить від того, чи включається кінцева точка в діапазон.")
print("Якщо `endpoint=True`, кінцева точка входить в діапазон, якщо `False` - не входить.")
print("Це змінює кількість елементів, що можуть бути рівномірно розподілені між початком і кінцем.")


Згенерували 10 чисел в діапазоні 5.0 до 100.0

>>>>> Виведіть кожне друге число згенерованого діапазону. Тут будее потрібен цикл :) 

Кожне друге число: 5.0
Кожне друге число: 26.11111111111111
Кожне друге число: 47.22222222222222
Кожне друге число: 68.33333333333333
Кожне друге число: 89.44444444444444
Можна зменшити кількість чисел до 5:
[  5.    28.75  52.5   76.25 100.  ]

>>>>> Збільшіть кількість чисел до 100. Виведіть перших та останніх 10. 

Перші 10 чисел: [ 5.          5.95959596  6.91919192  7.87878788  8.83838384  9.7979798
 10.75757576 11.71717172 12.67676768 13.63636364]
Останні 10 чисел: [ 91.36363636  92.32323232  93.28282828  94.24242424  95.2020202
  96.16161616  97.12121212  98.08080808  99.04040404 100.        ]
Як бачимо перше та останнє значення завжди входять у згенерований діапазон. 
Відповідно при цьому вираховується крок.
Це можна змінити, виключивши останнє значення з визначення діапазону.

[ 5. 24. 43. 62. 81.]

>>>>> Спробуйте самі порахувати крок. 

Розрах

### Типи масивів/векторів - COMPLETED

In [6]:
examples = {
    'Скаляр': np.array(1), 
    'Вектор Рядок': np.array([1, 2, 3]), 
    'Вектор Стовпець': np.array([[1], [2], [3]]), 
    'Матриця': np.array([[1, 2],[3, 4], [5, 6]]),
    'Багатовимірна Матриця': np.array([ [[111, 112], [121, 122]],
                                        [[211, 212], [221, 222]],
                                        [[311, 312], [321, 322]] ])
    }
for key in examples:
    print(f"Розглядаємо приклад з {key}. \nЗначення x буде: \n", examples[key])
    print(f"Тип {key} x: ", type(examples[key]))
    print(f"Розмірність/вимір {key} x:", np.ndim(examples[key]))
    print(f"Форма {key} x: ", examples[key].shape)
    print(f"Кількість елементів х: {np.size(examples[key])}")
    print("-=-"*10)

# Завдання 1:
homework("""Як Ви думаєте чому маємо такий результат для функції np.ndim (Розмірність/вимір/dimension).
Чому значення для векторів та матриць однакове та не співпдає з значенням shape?
Задайте власні вектори з різними числами.""")

print("1. Функція np.ndim повертає кількість вимірів (осей) масиву. Вона показує, скільки напрямків має масив, але не дає інформації про кількість елементів в кожному вимірі. Наприклад, для скаляра (масив з одним елементом) результат буде 0, для вектора (одновимірного масиву) - 1, а для матриці (двовимірного масиву) - 2.")

print("2. Значення для функції np.ndim та shape можуть не співпадати, оскільки np.ndim визначає кількість вимірів масиву (наприклад, 1 для вектора, 2 для матриці), а shape дає форму масиву, тобто кількість елементів у кожному вимірі. Наприклад, вектор може мати shape (3,) (тобто 3 елементи в одному вимірі), але np.ndim покаже 1.")

vector_1 = np.array([1, 2, 3, 4, 5])
vector_2 = np.array([[10], [20], [30]])
matrix_1 = np.array([[5, 10], [15, 20], [25, 30]])

print("3. Власні вектори та матриці:")
print("Вектор 1 (Рядок):", vector_1)
print("Тип:", type(vector_1))
print("Розмірність:", np.ndim(vector_1))
print("Форма:", vector_1.shape)
print("Кількість елементів:", np.size(vector_1))

print("\nВектор 2 (Стовпець):", vector_2)
print("Тип:", type(vector_2))
print("Розмірність:", np.ndim(vector_2))
print("Форма:", vector_2.shape)
print("Кількість елементів:", np.size(vector_2))

print("\nМатриця 1:", matrix_1)
print("Тип:", type(matrix_1))
print("Розмірність:", np.ndim(matrix_1))
print("Форма:", matrix_1.shape)
print("Кількість елементів:", np.size(matrix_1))


Розглядаємо приклад з Скаляр. 
Значення x буде: 
 1
Тип Скаляр x:  <class 'numpy.ndarray'>
Розмірність/вимір Скаляр x: 0
Форма Скаляр x:  ()
Кількість елементів х: 1
-=--=--=--=--=--=--=--=--=--=-
Розглядаємо приклад з Вектор Рядок. 
Значення x буде: 
 [1 2 3]
Тип Вектор Рядок x:  <class 'numpy.ndarray'>
Розмірність/вимір Вектор Рядок x: 1
Форма Вектор Рядок x:  (3,)
Кількість елементів х: 3
-=--=--=--=--=--=--=--=--=--=-
Розглядаємо приклад з Вектор Стовпець. 
Значення x буде: 
 [[1]
 [2]
 [3]]
Тип Вектор Стовпець x:  <class 'numpy.ndarray'>
Розмірність/вимір Вектор Стовпець x: 2
Форма Вектор Стовпець x:  (3, 1)
Кількість елементів х: 3
-=--=--=--=--=--=--=--=--=--=-
Розглядаємо приклад з Матриця. 
Значення x буде: 
 [[1 2]
 [3 4]
 [5 6]]
Тип Матриця x:  <class 'numpy.ndarray'>
Розмірність/вимір Матриця x: 2
Форма Матриця x:  (3, 2)
Кількість елементів х: 6
-=--=--=--=--=--=--=--=--=--=-
Розглядаємо приклад з Багатовимірна Матриця. 
Значення x буде: 
 [[[111 112]
  [121 122]]

 [[211 

### Багатовимірні масиви, розуміння вимірів - COMPLETED

In [7]:
# Приклади масивів
examples = {
    '5 рядків': np.array([[1], [2], [3], [4], [5]]), 
    '5 стовпців': np.array([[1, 2, 3, 4, 5]]),
    '5 елементів': np.array([[[1, 2, 3, 4, 5]]])
}

for a in examples:
    print(f"Для {a} маємо shape: \n{examples[a].shape} \nта вигляд: \n{examples[a]}")
    # Пояснення для кожного масиву
    print(f"Тип масиву для {a}: {type(examples[a])}")
    print(f"Кількість вимірів (np.ndim): {np.ndim(examples[a])}")
    print("-="*20)

# Завдання 1:
homework(f"Створіть власні масиви з різною кількістю елементів та використайте метод shape для визначення їх вимірів.")

# Створюємо власні масиви
array_1 = np.array([1, 2, 3, 4])  # Одновимірний масив
array_2 = np.array([[1, 2, 3], [4, 5, 6]])  # Двовимірний масив
array_3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])  # Тривимірний масив

# Виведення результатів
print(f"Масив 1 (одновимірний): shape = {array_1.shape}, вигляд: \n{array_1}")
print(f"Масив 2 (двовимірний): shape = {array_2.shape}, вигляд: \n{array_2}")
print(f"Масив 3 (тривимірний): shape = {array_3.shape}, вигляд: \n{array_3}")


Для 5 рядків маємо shape: 
(5, 1) 
та вигляд: 
[[1]
 [2]
 [3]
 [4]
 [5]]
Тип масиву для 5 рядків: <class 'numpy.ndarray'>
Кількість вимірів (np.ndim): 2
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Для 5 стовпців маємо shape: 
(1, 5) 
та вигляд: 
[[1 2 3 4 5]]
Тип масиву для 5 стовпців: <class 'numpy.ndarray'>
Кількість вимірів (np.ndim): 2
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Для 5 елементів маємо shape: 
(1, 1, 5) 
та вигляд: 
[[[1 2 3 4 5]]]
Тип масиву для 5 елементів: <class 'numpy.ndarray'>
Кількість вимірів (np.ndim): 3
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=

>>>>> Створіть власні масиви з різною кількістю елементів та використайте метод shape для визначення їх вимірів. 

Масив 1 (одновимірний): shape = (4,), вигляд: 
[1 2 3 4]
Масив 2 (двовимірний): shape = (2, 3), вигляд: 
[[1 2 3]
 [4 5 6]]
Масив 3 (тривимірний): shape = (2, 2, 2), вигляд: 
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Indexing and Slicing - COMPLETED

In [8]:
F = np.array([1, 1, 2, 3, 5, 8, 13, 21])
print(f"""Масив: {F}
Виміри: {F.shape}
Пам'ятаємо, що номерація масивів відбувається з 0.
Тому перший елемент масиву:\n {F[0]}  # Перший елемент, індекс 0
Другий:\n {F[1]}  # Другий елемент, індекс 1
Останній, {len(F)}: \n {F[7]}  # Останній елемент, індекс 7, або можна використовувати F[-1]""")

print(f"""Можемо скористатись від'ємними індексами, якщо хочемо доступитись до елементів з кінця масиву.
Але номерація вже з 1.
Тому останній елемент:\n {F[-1]}  # Останній елемент, індекс -1
Передостанній:\n {F[-2]}  # Передостанній елемент, індекс -2""")

# Завдання 1:
homework("""Попрактикуйтесь доступатись до елементів, виведіть декілька елементів різними способами.
Наприклад, можна вивести підмасиви за допомогою зрізів (slicing) чи використовувати від'ємні індекси.""")

F = np.array([1, 1, 2, 3, 5, 8, 13, 21])

# Виведемо перші 3 елементи за допомогою зрізу
print("Перші 3 елементи (індекси 0, 1, 2):", F[:3])

# Виведемо елементи з 2-го по 5-й (індекси 2, 3, 4)
print("Елементи з індексами 2, 3, 4:", F[2:5])

# Виведемо кожен другий елемент за допомогою кроку
print("Кожен другий елемент:", F[::2])

# Виведемо елементи з 3-го по 7-й (індекси 3, 4, 5, 6)
print("Елементи з індексами з 3 по 7:", F[3:8])

# Виведемо останні 3 елементи за допомогою від'ємних індексів
print("Останні 3 елементи (від'ємні індекси):", F[-3:])

# Виведемо передостанній елемент за допомогою від'ємного індексу
print("Передостанній елемент (від'ємний індекс):", F[-2])

# Виведемо елементи в зворотному порядку
print("Елементи у зворотньому порядку:", F[::-1])

Масив: [ 1  1  2  3  5  8 13 21]
Виміри: (8,)
Пам'ятаємо, що номерація масивів відбувається з 0.
Тому перший елемент масиву:
 1  # Перший елемент, індекс 0
Другий:
 1  # Другий елемент, індекс 1
Останній, 8: 
 21  # Останній елемент, індекс 7, або можна використовувати F[-1]
Можемо скористатись від'ємними індексами, якщо хочемо доступитись до елементів з кінця масиву.
Але номерація вже з 1.
Тому останній елемент:
 21  # Останній елемент, індекс -1
Передостанній:
 13  # Передостанній елемент, індекс -2

>>>>> Попрактикуйтесь доступатись до елементів, виведіть декілька елементів різними способами.
Наприклад, можна вивести підмасиви за допомогою зрізів (slicing) чи використовувати від'ємні індекси. 

Перші 3 елементи (індекси 0, 1, 2): [1 1 2]
Елементи з індексами 2, 3, 4: [2 3 5]
Кожен другий елемент: [ 1  2  5 13]
Елементи з індексами з 3 по 7: [ 3  5  8 13 21]
Останні 3 елементи (від'ємні індекси): [ 8 13 21]
Передостанній елемент (від'ємний індекс): 13
Елементи у зворотньому порядку: 

In [9]:
A = np.array([ [3.4, 8.7, 9.9], 
               [1.1, -7.8, -0.7],
               [4.1, 12.3, 4.8],
               [7.0, -3.9, 5.1]])

print(f"""Масив:
{A}
Виміри: {A.shape}
Принцип номерації такий самий, ТІЛЬКИ:
Якщо задати одне значення то візьметься цілий рядок:
    Перший рядок: {A[0]}
    Останній рядок: {A[-1]}
Для того щоб взяти цілий стовпець (символ : вказує взяти всі елементи): 
    Перший стовпець: {A[:,0]}
    Останній стовпець: {A[:,-1]}
Потрібно задавати два значення для отримання конкретного елемента: 
    Перший елемент: {A[0][0]} або {A[0, 0]}
    Останній елемент: {A[3][2]} або {A[-1][-1]} або {A[3, -1]}
""")

# Завдання 1:
homework("Попрактикуйтесь в доступі до багатовимірного масиву, виведіть елементів які належать діагоналі.")

# Виведемо елементи, які належать діагоналі масиву
# Діагональні елементи мають однакові індекси по ряду та стовпцю, отже, це A[i, i] для кожного i
print("Елементи на діагоналі масиву:")
min_dim = min(A.shape[0], A.shape[1])  # Визначимо мінімум між кількістю рядків і стовпців
for i in range(min_dim):  # Обмежуємо цикл до мінімуму між кількістю рядків та стовпців
    print(f"Елемент на діагоналі з індексом ({i},{i}): {A[i, i]}")

Масив:
[[ 3.4  8.7  9.9]
 [ 1.1 -7.8 -0.7]
 [ 4.1 12.3  4.8]
 [ 7.  -3.9  5.1]]
Виміри: (4, 3)
Принцип номерації такий самий, ТІЛЬКИ:
Якщо задати одне значення то візьметься цілий рядок:
    Перший рядок: [3.4 8.7 9.9]
    Останній рядок: [ 7.  -3.9  5.1]
Для того щоб взяти цілий стовпець (символ : вказує взяти всі елементи): 
    Перший стовпець: [3.4 1.1 4.1 7. ]
    Останній стовпець: [ 9.9 -0.7  4.8  5.1]
Потрібно задавати два значення для отримання конкретного елемента: 
    Перший елемент: 3.4 або 3.4
    Останній елемент: 5.1 або 5.1 або 5.1


>>>>> Попрактикуйтесь в доступі до багатовимірного масиву, виведіть елементів які належать діагоналі. 

Елементи на діагоналі масиву:
Елемент на діагоналі з індексом (0,0): 3.4
Елемент на діагоналі з індексом (1,1): -7.8
Елемент на діагоналі з індексом (2,2): 4.8


In [10]:
S = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

print(f"""Масив:
{S}
Виміри: {S.shape}
Беремо декілька елементів: {S[2:5]}
Всі елементи до заданого: {S[:4]}
Всі елементи від заданого до кінця: {S[6:]}
Всі елементи: {S[:]}
""")

# Завдання 1:
homework("Попрактикуйтесь у витягуванні елементів, візьміть 4 значення з кінця масиву.")

# Витягнемо 4 останні елементи з масиву
print("Останні 4 елементи масиву:")
print(S[-4:])

Масив:
[0 1 2 3 4 5 6 7 8 9]
Виміри: (10,)
Беремо декілька елементів: [2 3 4]
Всі елементи до заданого: [0 1 2 3]
Всі елементи від заданого до кінця: [6 7 8 9]
Всі елементи: [0 1 2 3 4 5 6 7 8 9]


>>>>> Попрактикуйтесь у витягуванні елементів, візьміть 4 значення з кінця масиву. 

Останні 4 елементи масиву:
[6 7 8 9]


In [11]:
A = np.array([
[11, 12, 13, 14, 15],
[21, 22, 23, 24, 25],
[31, 32, 33, 34, 35],
[41, 42, 43, 44, 45],
[51, 52, 53, 54, 55]])

print(f"""Масив:
{A}
Виміри: {A.shape}
Беремо декілька рядків: 
{A[0:2]}
Два перші стовпці: 
{A[:, 0:2]}
Два останні рядки:
{A[3:, :]}
Беремо підматрицю (нижні елементи): 
{A[-3:, -3:]}
""")

# Завдання 1:
homework("Попрактикуйтесь у витягуванні елементів, візьміть матрицю 2х2 з нижнього та верхнього кутка матриці А.")

# Витягнемо матрицю 2x2 з верхнього лівого кута
upper_left = A[:2, :2]
# Витягнемо матрицю 2x2 з нижнього правого кута
lower_right = A[-2:, -2:]

print(f"Матриця 2x2 з верхнього лівого кута:\n{upper_left}")
print(f"Матриця 2x2 з нижнього правого кута:\n{lower_right}")

Масив:
[[11 12 13 14 15]
 [21 22 23 24 25]
 [31 32 33 34 35]
 [41 42 43 44 45]
 [51 52 53 54 55]]
Виміри: (5, 5)
Беремо декілька рядків: 
[[11 12 13 14 15]
 [21 22 23 24 25]]
Два перші стовпці: 
[[11 12]
 [21 22]
 [31 32]
 [41 42]
 [51 52]]
Два останні рядки:
[[41 42 43 44 45]
 [51 52 53 54 55]]
Беремо підматрицю (нижні елементи): 
[[33 34 35]
 [43 44 45]
 [53 54 55]]


>>>>> Попрактикуйтесь у витягуванні елементів, візьміть матрицю 2х2 з нижнього та верхнього кутка матриці А. 

Матриця 2x2 з верхнього лівого кута:
[[11 12]
 [21 22]]
Матриця 2x2 з нижнього правого кута:
[[44 45]
 [54 55]]


In [12]:
A = np.arange(28).reshape(4, 7)

print(f"""Масив:
{A}
Виміри: {A.shape}
Беремо кожен дугий елемент першого рядка: 
{A[0, ::2]}
Беремо кожен третій елемент першого рядка: 
{A[0, ::3]}
Кожен другий елемент в кожному другому рядку: 
{A[::2, ::2]}
Останні три елементи в кожному другому рядку:
{A[::2, 4:]}
Можна повнісню змінити порядок елементів (дзерально обернемо):
{A[::-1, ::-1]}
""")

# Завдання 1:
homework("Попрактикуйтесь у витягуванні елементів, будь-яка робоча комбінація.")

# Приклад: витягнемо елементи, що розташовані на парних індексах з кожного непарного рядка
print(f"Парні елементи з непарних рядків: {A[1::2, ::2]}")

# Приклад: витягнемо всі елементи з останнього стовпця
print(f"Елементи останнього стовпця: {A[:, -1]}")

# Приклад: витягнемо елементи, де значення більші за 15
print(f"Елементи більші за 15: {A[A > 15]}")

Масив:
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]]
Виміри: (4, 7)
Беремо кожен дугий елемент першого рядка: 
[0 2 4 6]
Беремо кожен третій елемент першого рядка: 
[0 3 6]
Кожен другий елемент в кожному другому рядку: 
[[ 0  2  4  6]
 [14 16 18 20]]
Останні три елементи в кожному другому рядку:
[[ 4  5  6]
 [18 19 20]]
Можна повнісню змінити порядок елементів (дзерально обернемо):
[[27 26 25 24 23 22 21]
 [20 19 18 17 16 15 14]
 [13 12 11 10  9  8  7]
 [ 6  5  4  3  2  1  0]]


>>>>> Попрактикуйтесь у витягуванні елементів, будь-яка робоча комбінація. 

Парні елементи з непарних рядків: [[ 7  9 11 13]
 [21 23 25 27]]
Елементи останнього стовпця: [ 6 13 20 27]
Елементи більші за 15: [16 17 18 19 20 21 22 23 24 25 26 27]


In [13]:
A = np.arange(50)
all_even = (A % 2 == 0)  # парні
complex = (A < 30) & (A / 5 < 2)

print(f"""Спочатку потрібно створити умову за якою здійснювати вибірку.
Результат умови буде або {all_even[0]} для {A[0]} або {all_even[1]} для {A[1]}.
Після підставляння умови пошуку парних чисел в масив отримаємо:
{A[all_even]}
Або застосувати більш комплексну умову з двох порівнянь:
{A[complex]}
""")

# Завдання 1:
homework("Виведіть всі непарні числа з даного масиву.")

# Виводимо непарні числа
all_odd = (A % 2 != 0)  # непарні
print(f"Непарні числа з масиву: {A[all_odd]}")

Спочатку потрібно створити умову за якою здійснювати вибірку.
Результат умови буде або True для 0 або False для 1.
Після підставляння умови пошуку парних чисел в масив отримаємо:
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]
Або застосувати більш комплексну умову з двох порівнянь:
[0 1 2 3 4 5 6 7 8 9]


>>>>> Виведіть всі непарні числа з даного масиву. 

Непарні числа з масиву: [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]


### Функції для створення матриць, arange, linspace, порівняння формул, створення простих векторів та матриць, операції над ними

In [14]:
o = np.ones(5)
z = np.zeros(5)
i = np.identity(5)
e = np.eye(5)
t = np.empty(5)

print(f"""
Всі елементи 1:
{o}
Всі елементи 0:
{z}
Матриця в якої діагональ всі 1:
{i}
Також, діагональ всі 1 (зменшимо вивід):
{e[:2, :2]}
Пуста матриця буде містити набір випадкових чисел які записані у память де був ініціалізований масив:
{t}
""")


Всі елементи 1:
[1. 1. 1. 1. 1.]
Всі елементи 0:
[0. 0. 0. 0. 0.]
Матриця в якої діагональ всі 1:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Також, діагональ всі 1 (зменшимо вивід):
[[1. 0.]
 [0. 1.]]
Пуста матриця буде містити набір випадкових чисел які записані у память де був ініціалізований масив:
[6.95277263e-310 9.34605715e-307 6.95277185e-310 6.95277183e-310
 7.62556346e-312]



### 1.1 Генерація значень за допомогою `arange`

Метод `arange` генерує значення з певним кроком між ними. Формула для значень, що генеруються методом `arange`, має вигляд:

start + n * step, де n = 0, 1, 2, ..., n_max-1


- `start` — початкове значення
- `step` — крок між елементами
- `n_max` — кількість елементів, яку поверне метод (для визначення останнього елемента, потрібно врахувати значення кроку та межі)

Наприклад, якщо `np.arange(0, 10, 2)` генерує `[0, 2, 4, 6, 8]`. Це значення починаються з 0 і збільшуються на 2.

### 1.2 Генерація значень за допомогою `linspace`

Метод `linspace` генерує рівномірно розподілені значення між заданими початковим та кінцевим значенням. Формула для значень, що генеруються методом `linspace`, виглядає так:

start + (end - start) * (i / (num - 1)), де i = 0, 1, 2, ..., num-1

## Порівняння методів `arange` і `linspace`

- **`arange`**: 
  Використовує крок між значеннями. Кількість значень залежить від величини кроку. Це зручно, коли ви знаєте точний крок між значеннями, але не знаєте точну кількість елементів у результаті.

- **`linspace`**: 
  Використовує кількість значень, які потрібно згенерувати, і рівномірно розподіляє їх між початковим і кінцевим значенням. Це зручно, коли потрібно отримати точну кількість значень на певному інтервалі.

### Коли застосовувати:
- **`arange`** краще застосовувати, коли вам потрібно згенерувати послідовність чисел з певним кроком.
- **`linspace`** корисніше, коли вам потрібно точно розподілити певну кількість значень між двома точками, наприклад, для побудови графіка чи розподілу точок на відрізку.


In [15]:
## Завдання 2: Створення Векторів та Матриць

### 2.1 Створення векторів та матриць

import numpy as np

# Вектор
vector = np.array([1, 2, 3, 4, 5])
print(f"Вектор: {vector}")
print(f"Розмірність вектора: {vector.shape}")

# Матриця 2x3
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(f"Матриця: \n{matrix}")
print(f"Розмірність матриці: {matrix.shape}")

# Вектор з нулями
vector_zeros = np.zeros(5)
print(f"Вектор з нулями: {vector_zeros}")
print(f"Розмірність: {vector_zeros.shape}")

# Матриця одиниць 3x3
matrix_ones = np.ones((3, 3))
print(f"Матриця одиниць: \n{matrix_ones}")
print(f"Розмірність: {matrix_ones.shape}")

### 2.2 Арифметичні операції над Векторами та Матрицями

# Арифметичні операції над векторами
vector_sum = vector + 5  # Додаємо 5 до кожного елементу вектора
vector_diff = vector - 1  # Віднімаємо 1 від кожного елементу
vector_prod = vector * 2  # Множимо кожен елемент на 2
vector_div = vector / 2  # Ділимо кожен елемент на 2

print(f"Вектор після додавання 5: {vector_sum}")
print(f"Вектор після віднімання 1: {vector_diff}")
print(f"Вектор після множення на 2: {vector_prod}")
print(f"Вектор після ділення на 2: {vector_div}")

# Арифметичні операції над матрицями
matrix_sum = matrix + 2  # Додаємо 2 до кожного елементу матриці
matrix_diff = matrix - 1  # Віднімаємо 1 від кожного елементу
matrix_prod = matrix * 3  # Множимо кожен елемент на 3
matrix_div = matrix / 2  # Ділимо кожен елемент на 2

print(f"Матриця після додавання 2: \n{matrix_sum}")
print(f"Матриця після віднімання 1: \n{matrix_diff}")
print(f"Матриця після множення на 3: \n{matrix_prod}")
print(f"Матриця після ділення на 2: \n{matrix_div}")

Вектор: [1 2 3 4 5]
Розмірність вектора: (5,)
Матриця: 
[[1 2 3]
 [4 5 6]]
Розмірність матриці: (2, 3)
Вектор з нулями: [0. 0. 0. 0. 0.]
Розмірність: (5,)
Матриця одиниць: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Розмірність: (3, 3)
Вектор після додавання 5: [ 6  7  8  9 10]
Вектор після віднімання 1: [0 1 2 3 4]
Вектор після множення на 2: [ 2  4  6  8 10]
Вектор після ділення на 2: [0.5 1.  1.5 2.  2.5]
Матриця після додавання 2: 
[[3 4 5]
 [6 7 8]]
Матриця після віднімання 1: 
[[0 1 2]
 [3 4 5]]
Матриця після множення на 3: 
[[ 3  6  9]
 [12 15 18]]
Матриця після ділення на 2: 
[[0.5 1.  1.5]
 [2.  2.5 3. ]]
